version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    volumes:
      - C:\Work\SoftwareDev\DLSSearchEngine:/data
    deploy:
      replicas: 2
    depends_on:
      - load-balancer
  web:
    build:
      context: .
      dockerfile: "WebSearch/Dockerfile"
    ports:
      - 9000-9010:80
    depends_on:
      - load-balancer
    deploy:
      replicas: 1
  load-balancer:
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - 9011:80
    deploy:
      replicas: 1
    